print(" "+"-"*48)
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Jennica Wang                         |")
print("|    Version : 01                                |")
print("|                                                |")
print(" "+"-"*48)
print("Hello World")
input("------> Program paused - press enter to continue")
print("Goodbye World")