print(" "+"-"*48)
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Jennica Wang                         |")
print("|    Version : 01                                |")
print("|                                                |")
print(" "+"-"*48)
print("Hello World")
x = input("What is your name ? ")
print("Goodbye "+x)